import logging
from pathlib import Path

from alembic.config import Config
from alembic.script import ScriptDirectory
from sqlalchemy import create_engine, inspect

from alembic import command
from finance_ai.config import PROJECT_ROOT
from finance_ai.db.backup import BackupError, create_backup
from finance_ai.db.database import get_engine

logger = logging.getLogger(__name__)

# The very first migration -- alembic/versions/..._baseline_schema.py -- was autogenerated
# from Base.metadata as it stood before migrations existed, so it's exactly the schema any
# pre-migration database already has. Hardcoded (rather than "whatever the base revision
# happens to be") so a later migration added after this one doesn't retroactively change
# what "baseline" means for someone upgrading from before migrations existed.
BASELINE_REVISION = "47853bbf34e1"


def _alembic_config(db_path: Path | str | None) -> Config:
    cfg = Config(str(PROJECT_ROOT / "alembic.ini"))

    if db_path is not None:
        cfg.set_main_option("sqlalchemy.url", f"sqlite:///{db_path}")
    # else: leave sqlalchemy.url unset here -- alembic/env.py falls back to the real
    # finance_ai.config.DB_PATH itself, the same path get_engine() uses.

    return cfg


def _make_engine(db_path: Path | str | None):
    if db_path is None:
        return get_engine()

    return create_engine(f"sqlite:///{db_path}", future=True)


def ensure_schema_up_to_date(
    db_path: Path | str | None = None,
    backup_before_upgrade: bool = True,
    backup_dir: Path | str | None = None,
) -> None:
    """Brings the database schema up to the latest migration. Handles three cases:

    - No database file yet, or one with no tables: a fresh install. Alembic creates every
      table from the baseline migration onward.
    - A database with the app's own tables but no alembic_version table: an existing
      install from before migrations were introduced. Stamped at BASELINE_REVISION (not
      "head") rather than having the baseline migration's CREATE TABLE statements run
      against tables that already exist -- correct because the baseline migration was
      autogenerated from exactly this schema. Stamping at the specific baseline revision,
      not "head", matters once more migrations exist after it: an upgrade() call
      immediately following the stamp still applies anything added since baseline, rather
      than silently skipping migrations a "stamp at head" would have skipped over.
    - A database that's already migration-tracked: a normal upgrade, applying whatever
      migrations exist beyond its current revision.

    Called on every app/CLI startup (idempotent, cheap once already current), so schema
    changes ship as ordinary migrations instead of requiring make reset-db to wipe the
    database -- known issue #2 in CLAUDE.md.

    db_path defaults to the real app database (finance_ai.config.DB_PATH via get_engine());
    only tests pass a different path.

    backup_before_upgrade takes an automatic backup when, and only when, migrations are
    actually going to be applied to a database that already holds data. Since this runs on
    every startup, backing up unconditionally would produce a backup per launch; gating it
    on "there is pending work to do" keeps it to the moments that carry real risk -- a
    schema change against real financial data.

    backup_dir defaults to the real BACKUP_DIR; it's a parameter for the same reason
    db_path is, so tests don't write into the user's actual backups directory.
    """

    engine = _make_engine(db_path)

    with engine.connect() as connection:
        table_names = inspect(connection).get_table_names()

    has_alembic_version = "alembic_version" in table_names
    has_app_tables = "accounts" in table_names

    cfg = _alembic_config(db_path)

    if backup_before_upgrade and has_app_tables:
        _backup_if_migrations_pending(db_path, backup_dir)

    if has_app_tables and not has_alembic_version:
        logger.info(
            "Existing pre-migration database detected -- stamping at baseline revision %s.",
            BASELINE_REVISION,
        )
        command.stamp(cfg, BASELINE_REVISION)

    command.upgrade(cfg, "head")


def _backup_if_migrations_pending(
    db_path: Path | str | None,
    backup_dir: Path | str | None,
) -> None:
    """A failed backup must not block the upgrade -- the schema still needs to come up to
    date for the app to work at all. Log loudly and continue rather than leaving the user
    with an app that won't start because a nice-to-have safety step failed."""

    if current_revision(db_path) == head_revision():
        return

    try:
        backup_path = create_backup(
            label="pre-migration", db_path=db_path, backup_dir=backup_dir
        )
        logger.info("Backed up database to %s before applying migrations.", backup_path)
    except BackupError:
        logger.exception("Could not back up the database before migrating; continuing anyway.")


def current_revision(db_path: Path | str | None = None) -> str | None:
    """The database's current migration revision, or None if it isn't migration-tracked yet."""

    engine = _make_engine(db_path)

    with engine.connect() as connection:
        table_names = inspect(connection).get_table_names()

        if "alembic_version" not in table_names:
            return None

        row = connection.exec_driver_sql("SELECT version_num FROM alembic_version").fetchone()
        return row[0] if row else None


def head_revision() -> str:
    """The latest revision the migration scripts define, regardless of any database's state."""

    script = ScriptDirectory.from_config(_alembic_config(None))
    return script.get_current_head()
