"""add essential spending flag and essential emergency fund fields

Revision ID: 781e54f0d618
Revises: 47853bbf34e1
Create Date: 2026-07-28 01:00:22.378423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781e54f0d618'
down_revision: Union[str, Sequence[str], None] = '47853bbf34e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_essential', sa.Boolean(), nullable=True))
    op.add_column('financial_snapshot_records', sa.Column('essential_monthly_expenses', sa.Float(), nullable=True))
    op.add_column('financial_snapshot_records', sa.Column('essential_emergency_fund_months', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_snapshot_records', 'essential_emergency_fund_months')
    op.drop_column('financial_snapshot_records', 'essential_monthly_expenses')
    op.drop_column('categories', 'is_essential')
    # ### end Alembic commands ###
